server:
  port: 8888
---
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
      format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    username: tester
    password: tester123
---
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    root: INFO